### ISSUE TITLE
[BUG]: feed.removeSubscriptions doesn't work

### ISSUE THREAD

**Issue by prodderman** [dxFeed/dxLink#1]
@Fyzu Hi, the client doesn't emit unsubscribe message

[Codesandbox](https://codesandbox.io/p/sandbox/recursing-tesla-gf4gqw) example

**Comment by prodderman** [comment]
UPDATE:
it seems you can subscribe/unsubscribe only once

**Comment by Fyzu** [comment]
Fixed
